---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: ns-dashboard

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backend-db
  hostPath:
    path: /mnt/db