---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-results-pv
  namespace: ns-dashboard

spec:
  capacity:
    storage: 17Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: backend-storage
  hostPath:
    path: /mnt/backend-results