---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-results-pvc
  namespace: ns-dashboard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: backend-storage